# Jupyter overview

In [ ]:
print('printed')

In [7]:
range(10000000)

range(0, 10000000)

In [8]:
list(range(10000000))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [1]:
#tool i dont know write ? at the end
list?

In [2]:
#when function has a bug in it, use it to debug
def hello():
    print ("python 2 is not here")
    foo = bar
hello()
%debug
#c continue q quit

python 2 is not here

NameError: name 'bar' is not defined

In [3]:
%debug

> <ipython-input-2-489ee450a143>(4)hello()
      2 def hello():
      3     print ("python 2 is not here")
----> 4     foo = bar
      5 hello()
      6 get_ipython().magic('debug')

ipdb> c

In [13]:
#what is faster?
# add _ = to not display list of numbers below
%time
_ = [ i for i in range(100)]

Wall time: 0 ns

In [12]:
#timeit gives statistical average after running a few times
%timeit _ = list(range(100))

1.01 µs ± 8.36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [15]:
#if i have a script and want to run it inside here
! echo "print('hello)" > mypython.py

In [17]:
ls

 Volume in drive C is OS
 Volume Serial Number is 2E1B-E1FF

 Directory of C:\Users\calka\Documents\Y4\python\Untitled Folder

09/11/2017  15:50    <DIR>          .
09/11/2017  15:50    <DIR>          ..
09/11/2017  15:36    <DIR>          .ipynb_checkpoints
09/11/2017  09:51       293,957,454 allrecipes-recipes.json
09/11/2017  12:23    <DIR>          bbccouk-recipes
09/11/2017  10:20        33,444,504 bbccouk-recipes.json
09/11/2017  15:50            26,440 Essential data science skills for every programmer, from data to model to visualization.ipynb
21/02/2017  09:57        35,249,903 full_format_recipes.json
09/11/2017  13:50         4,396,625 github-allrecipes.data
09/11/2017  15:50                18 mypython.py
09/11/2017  14:00           152,336 TestingData.ipynb
               7 File(s)    367,227,280 bytes
               4 Dir(s)  424,140,009,472 bytes free

In [18]:
%run mypython.py

### ESC + M = makes cell a markdown

# Pandas

In [ ]:
%matplotlib inline 
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import bokeh
from bokeh.io import output_notebook, show
output_notebook()

import pandas as pd
print ("Pandas version: {}".format(pd.__version__))

In [23]:
#edit display options
pd.options.display.max_rows = 6
pd.options.display.max_columns = 8
pd.options.display.width = 100

## reading and writing data

In [27]:
#import json from zipped file
import gzip
review_lines = gzip.open('reviews_Clothing_Shoes_and_Jewelry_5.json.gz', 'rt').readlines()
len(review_lines)

278677

now we have something, but it's a lot of lines. So we load it into a DataFrame, an object that is the data hacker's go to for manipulating structured data.
Unfortunately, its not as straight forward as pd.read_json, since first we have to turn all those JSON strings into Python objects, so let's turn each into a dict and then build a DataFrame

In [42]:
import json
df_reviews = pd.DataFrame(list(map(json.loads, review_lines)))

In [29]:
df_reviews.head()

,asin,helpful,overall,reviewText,...,reviewerID,reviewerName,summary,unixReviewTime
0,0000031887,"[0, 0]",5.0,This is a great tutu and at a really great pri...,...,A1KLRMWW2FWPL4,"Amazon Customer ""cameramom""",Great tutu- not cheaply made,1297468800
1,0000031887,"[0, 0]",5.0,I bought this for my 4 yr old daughter for dan...,...,A2G5TCU2WDFZ65,Amazon Customer,Very Cute!!,1358553600
2,0000031887,"[0, 0]",5.0,What can I say... my daughters have it in oran...,...,A1RLQXYNCMWRWN,Carola,I have buy more than one,1357257600
3,0000031887,"[0, 0]",5.0,"We bought several tutus at once, and they are ...",...,A8U3FAMSJVHS5,Caromcg,"Adorable, Sturdy",1398556800
4,0000031887,"[0, 0]",5.0,Thank you Halo Heaven great product for Little...,...,A3GEOILWLK86XM,CJ,Grammy's Angels Love it,1394841600

In [ ]:
#export to csv
#df_reviews.to_csv("filename.csv")

In [32]:
# add ! in front  to use command line commands
!dir

 Volume in drive C is OS
 Volume Serial Number is 2E1B-E1FF

 Directory of C:\Users\calka\Documents\Y4\python\Untitled Folder

09/11/2017  16:18    <DIR>          .
09/11/2017  16:18    <DIR>          ..
09/11/2017  15:36    <DIR>          .ipynb_checkpoints
09/11/2017  09:51       293,957,454 allrecipes-recipes.json
09/11/2017  12:23    <DIR>          bbccouk-recipes
09/11/2017  10:20        33,444,504 bbccouk-recipes.json
09/11/2017  16:15        30,105,478 bbcrecipes.csv
09/11/2017  16:18            53,338 Essential data science skills for every programmer, from data to model to visualization.ipynb
21/02/2017  09:57        35,249,903 full_format_recipes.json
09/11/2017  13:50         4,396,625 github-allrecipes.data
09/11/2017  15:50                18 mypython.py
09/11/2017  16:01        47,285,200 reviews_Clothing_Shoes_and_Jewelry_5.json.gz
09/11/2017  16:18           115,915 TestingData.ipynb
               9 File(s)    444,608,435 bytes
               4 Dir(s)  424,048,865,280 bytes free

### info - how many entries, column names, what type they have

In [35]:

df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278677 entries, 0 to 278676
Data columns (total 9 columns):
asin              278677 non-null object
helpful           278677 non-null object
overall           278677 non-null float64
reviewText        278677 non-null object
reviewTime        278677 non-null object
reviewerID        278677 non-null object
reviewerName      278225 non-null object
summary           278677 non-null object
unixReviewTime    278677 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 19.1+ MB

### change data type

In [51]:
# unixReviewTime - we want to understand it as a date time, because we want to do date time operations on it
df_reviews['unixReviewTime'] = pd.to_datetime(df_reviews['unixReviewTime'], unit='s')

# working with text data

In [36]:
df_reviews.summary

0                             Great tutu-  not cheaply made
1                                               Very Cute!!
2                                  I have buy more than one
                                ...
278674                 Convenient, lightweight, and durable
278675                     Holds Up Well In Real World Test
278676    Don't Travel? Still Way too Useful for 'Averag...
Name: summary, Length: 278677, dtype: object

In [39]:
#string length
df_reviews.summary.str.len()

0         29
1         11
2         24
          ..
278674    36
278675    32
278676    52
Name: summary, Length: 278677, dtype: int64

In [44]:
df_reviews.summary.str.upper().str.contains("GREAT")

0          True
1         False
2         False
          ...
278674    False
278675    False
278676    False
Name: summary, Length: 278677, dtype: bool

## WORKING WITH TIMESERIES DATA
#### dt.accessor
- you can access days, weeks and a lot more

In [55]:
df_reviews.unixReviewTime.dt.weekofyear

0          6
1          3
2          1
          ..
278674    23
278675    28
278676    26
Name: unixReviewTime, Length: 278677, dtype: int64

In [53]:
df_reviews.unixReviewTime.dt.dayofweek

0         5
1         5
2         4
         ..
278674    6
278675    0
278676    0
Name: unixReviewTime, Length: 278677, dtype: int64

## Booleand Indexing

Like a where clause in SQL, you can filter the dataframe with a boolean index, e.g.

In [56]:
df_reviews.overall < 5

0         False
1         False
2         False
          ...
278674    False
278675    False
278676    False
Name: overall, Length: 278677, dtype: bool

In [58]:
df_reviews[df_reviews.overall < 5]

,asin,helpful,overall,reviewText,...,reviewerID,reviewerName,summary,unixReviewTime
5,0000031887,"[0, 0]",4.0,I received this today and I'm not a fan of it ...,...,A27UF1MSF3DB2,"C-Lo ""Cynthia""",It's ok,2014-03-31
8,0000031887,"[0, 0]",4.0,"My daughter liked this, and it with her costum...",...,A1NJ71X3YPQNQ9,JBerger,Good,2013-11-10
15,0000031887,"[0, 0]",3.0,My 3yr old loved this tutu skirt in pink! Was ...,...,A26A4KKLAVTMCC,Moonlight,Came apart in 2weeks!,2014-03-20
...,...,...,...,...,...,...,...,...,...
278657,B00KF9180W,"[4, 5]",4.0,I go walking a lot in all kinds of weather and...,...,A1EVV74UQYVKRY,K. Groh,Great for Winter or Chilly Walks,2014-06-16
278662,B00KF9180W,"[2, 3]",4.0,"Nice material, but not as nice as silk or mer...",...,A3UJRNI8UR4871,"Wulfstan ""wulfstan""",Lightweight & useful,2014-06-09
278663,B00KGCLROK,"[1, 1]",2.0,These were a free sample for review. I was ex...,...,A34BZM6S9L7QI4,"Candy Cane ""Is it just me?""",Wanted to love these,2014-06-21